#!/usr/bin/env python3
import argparse
import sys

from trees import build_bst, build_avl
from tree_print import print_tree
from tree_search import find_min_max
from tree_export import export_tree
from tree_remove import remove_elements
from tree_delete_all import delete_all


def print_help():
    print("Help \tShow this message")
    print("Print \tPrint the tree (in-order, pre-order, post-order)")
    print("Search \tFind min and max values in the tree")
    print("Remove \tRemove elements of the tree")
    print("Delete \tDelete whole tree")
    print("Export \tExport the tree to tikzpicture")
    print("Rebalance \tRebalance the tree")
    print("Exit \tExits the program (same as Ctrl+D)")

def main():
    parser = argparse.ArgumentParser(description="Drzewa przeszukiwań binarnych")
    parser.add_argument("--tree", choices=["BST", "AVL"], required=True, help="Wybierz typ drzewa")
    args = parser.parse_args()

    try:
        # -------- Pytanie o węzły i parsowanie wpisanych liczb na liste intow ------- #
        nodes_input = input("nodes> ")
        values = [int(x) for x in nodes_input.split()]

        # -------------- Budowanie drzewa za pomocja funkcji z trees.py -------------- #
        if args.tree == "BST":
            root = build_bst(values)
        else:
            root = build_avl(values)

        while True:
            action_input = input("action> ").strip()
            action = action_input.lower()

            if action == "help":
                print_help()
            elif action == "print":
                print_tree(root)
            elif action == "search":
                find_min_max(root)
            elif action == "remove":
                remove_input = input("remove> ")
                values_to_remove = [int(x) for x in remove_input.split()]
                root = remove_elements(root, values_to_remove)
            elif action == "delete":
                root = delete_all(root)
            elif action == "export":
                export_tree(root)
            elif action == "rebalance":
                pass 
            elif action in ["exit", ""]:
                break
            else:
                pass

    except EOFError:
        pass
    except KeyboardInterrupt:
        print()
    
    print("Program exited with status: 0")

if __name__ == "__main__":
    main()